// Code generated by Thrift Compiler (0.14.0). DO NOT EDIT.

package edgecontext

import(
	"bytes"
	"context"
	"reflect"
	"fmt"
	"time"
	"github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = time.Now
var _ = bytes.Equal


func init() {
}

